version: 1.0.{build}
image: Visual Studio 2019
build_script:
- cmd: >-
    dotnet pack -c Release .\src\Ternacode.Persistence.Abstractions

    dotnet pack -c Release .\src\Ternacode.Persistence.EntityFrameworkCore
test_script:
- cmd: dotnet test .\test\Ternacode.Persistence.EntityFrameworkCore.UnitTest
artifacts:
- path: src\Ternacode.Persistence.Abstractions\bin\Release\Ternacode.Persistence.Abstractions.*.nupkg
  name: Abstractions nupkg
- path: src\Ternacode.Persistence.EntityFrameworkCore\bin\Release\Ternacode.Persistence.EntityFrameworkCore.*.nupkg
  name: EntityFrameworkCore nupkg
deploy:
- provider: NuGet
  api_key:
    secure: f7CCzxJvDCaSgLD9gykJWTsXguPr1MCqcHs7RQYZVkejLKPsM/IaRlpp6yGLNQTE
  skip_symbols: true
  artifact: src\Ternacode.Persistence.Abstractions\bin\Release\Ternacode.Persistence.Abstractions.*.nupkg
  on:
    branch: master
- provider: NuGet
  api_key:
    secure: f7CCzxJvDCaSgLD9gykJWTsXguPr1MCqcHs7RQYZVkejLKPsM/IaRlpp6yGLNQTE
  skip_symbols: true
  artifact: src\Ternacode.Persistence.EntityFrameworkCore\bin\Release\Ternacode.Persistence.EntityFrameworkCore.*.nupkg
  on:
    branch: master