version: 1.0.{build}
image: Visual Studio 2019
build_script:
- cmd: >-
    dotnet pack -c Release .\src\Ternacode.Persistence.Abstractions
    
    dotnet pack -c Release .\src\Ternacode.Persistence.EntityFrameworkCore
    
    dotnet pack -c Release .\src\Ternacode.Persistence.Extensions
test_script:
- cmd: dotnet test .\test\Ternacode.Persistence.EntityFrameworkCore.UnitTest
artifacts:
- path: src\Ternacode.Persistence.Abstractions\bin\Release\Ternacode.Persistence.Abstractions.*.nupkg
  name: Abstractions nupkg
- path: src\Ternacode.Persistence.EntityFrameworkCore\bin\Release\Ternacode.Persistence.EntityFrameworkCore.*.nupkg
  name: EntityFrameworkCore nupkg
- path: src\Ternacode.Persistence.Extensions\bin\Release\Ternacode.Persistence.Extensions.*.nupkg
  name: Extensions nupkg
deploy:
- provider: NuGet
  api_key:
    secure: bhug3NhltmaZJu0x/aksJsfIrlPeXi0MWy9nj+pCM0VM1mIhXJ54F5pgAWmH8WXj
  skip_symbols: true
  artifact: /.*\.nupkg/
  on:
    branch: master