// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Ternacode.Persistence.Example.Database.Migrations
{
    [DbContext(typeof(BlogContext))]
    partial class BlogContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Ternacode.Persistence.Example.Domain.Model.Post", b =>
                {
                    b.Property<Guid>("PostId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset>("CreatedOn");

                    b.Property<string>("Title");

                    b.HasKey("PostId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("Ternacode.Persistence.Example.Domain.Model.PostAuthor", b =>
                {
                    b.Property<Guid>("PostAuthorId")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AuthorUserId");

                    b.Property<Guid?>("PostId");

                    b.HasKey("PostAuthorId");

                    b.HasIndex("AuthorUserId");

                    b.HasIndex("PostId");

                    b.ToTable("PostAuthor");
                });

            modelBuilder.Entity("Ternacode.Persistence.Example.Domain.Model.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Ternacode.Persistence.Example.Domain.Model.PostAuthor", b =>
                {
                    b.HasOne("Ternacode.Persistence.Example.Domain.Model.User", "Author")
                        .WithMany("AuthoredPosts")
                        .HasForeignKey("AuthorUserId");

                    b.HasOne("Ternacode.Persistence.Example.Domain.Model.Post", "Post")
                        .WithMany("Authors")
                        .HasForeignKey("PostId");
                });
#pragma warning restore 612, 618
        }
    }
}
